name: "Update webpage"
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      # https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy 🚀
        uses: rocknbirra/github-pages-deploy-action@v4
        with:
          branch: main # The branch the action should deploy to.
          folder: build # The folder the action should deploy.