name: Skip Artifact

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache specific folders
        uses: actions/cache@v3
        with:
          path: |
            images/21-07-23/
            images/22-07-23/
            images/24-07-23/
            images/25-07-23/
          key: ${{ runner.os }}-images-${{ hashFiles('images/21-07-23/**') }}-${{ hashFiles('images/22-07-23/**') }}-${{ hashFiles('images/24-07-23/**') }}
          #-${{ hashFiles('images/25-07-23/**') }}
          # Add more hashFiles entries for additional folders
      # Add more steps here if needed for your workflow

      # Step 2: Upload artifact, but only if specific condition is met
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: unnecessary  # Customize the name of your artifact
          path: build/dist/     # Customize the path to your artifact

        # Condition to skip the upload step
        if: false