name: Skip Artifact

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Upload artifact, but only if specific condition is met
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: unnecessary  # Customize the name of your artifact
          path: build/dist/     # Customize the path to your artifact

        # Condition to skip the upload step
        if: false
